apiVersion: v1
kind: Secret
metadata:
  name: artifactory-regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: >
    {{ printf "{\"auths\": {\"%s\": {\"username\":\"%s\", \"password\":\"%s\", \"auth\": \"%s\"}}}"
      .Values.artifactory.server
      .Values.artifactory.username
      .Values.artifactory.password
      (printf "%s:%s" .Values.artifactory.username .Values.artifactory.password | b64enc)
      | b64enc }}
