apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-spring-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}-spring-petclinic